on: [push, pull_request]

name: Continuous integration

jobs:
  primary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - run: cargo build

      - run: cargo test

      - run: cargo fmt --all -- --check

      - run: cargo clippy -- -D warnings

  secondary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
          - nightly
          - 1.56.0

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - run: cargo build

      - run: cargo test

  features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
        features:
          - unstable
          # - compile_failure # Currently not clean

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - run: cargo build --features ${{ matrix.features }}

      - run: cargo test--features ${{ matrix.features }}

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - run: cargo build

      - run: cargo test
